name: Orca Qualys scan
description: Composite action for orca qualys scan
author: DA Team <da.team@sherwin.com>

inputs: 
  config_id:
    required: true
    description: Provide the orca config id for Qualys
    
  orca_api_key:
    required: true
    description: Provide Orca API KEY
  
  orca_url:
    required: false
    default: 'https://orca.sherwin.com/api/v2/task/'
    
  request_timeout: 
    required: false
    default: 20000
    description: Provide the http requst timeout. Defaults to 20s
   
outputs:
  response: 
     description: Orca Qualys scan Http response 
     value: ${{ steps.post.outputs.response }}
runs:
  using: "composite"
  steps: 
  
    - name: Orca HTTP Request Action
      id: post
      uses: fjogeleit/http-request-action@v1.9.1
      with:
        url: ${{ inputs.orca_url }}
        data: {"config": ${{ inputs.config_id }} }
        method: 'POST'
        bearerToken: '${{ inputs.orca_api_key }}'
        timeout: ${{ inputs.request_timeout }}
        
#     - name: Show Response
#       run: echo ${{ steps.post.outputs.response }}
#       shell: bash
      
branding:
  icon: git-branch
  color: white
